project:
  type: website
  output-dir: docs

website:
  title: "midvie"
  navbar:
    title: "mid<span class='logo-v'>v</span>ie<span class='logo-line'></span>"
    background: light
    left:
      - text: Home
        href: index.qmd
      - text: News
        href: news.qmd
      - text: People
        href: people.qmd
      - text: Blog
        href: blog.qmd

format:
  html:
    theme: [flatly, custom.scss]
    css: styles.css
    toc: true



