project:
  type: website
  output-dir: docs

website:
  title: "MIDVIE"
  navbar:
    background: light
    left:
      - text: Home
        href: index.qmd
      - text: People
        href: people.qmd
      - text: Blog
        href: blog.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



